[build]
  command = "npm run build"  # Adjust if using a different build command
  publish = "build"          # Use "dist" for Vue, "build" for React, etc.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
